# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tao SandBoxs
tagline: 'Journal, TIL, Documenting'
email: soukoulis.tasos@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Documenting my progress as I learn programming and computer science.
  Topics: C, JS, Rust, Datastructures, computer science, life and tackling problems.
baseurl: "" # the subpath of your site, e.g. /blog
permalink: pretty
url: "http://taosx.github.io" # the base hostname & protocol for your site
twitter_username: taosx
github_username:  taosx
paginate: 5

sass:
  sass_dir: _sass
  style: :compressed

# Build settings
markdown: kramdown

gems:
  - jekyll-paginate
  - jekyll-gist